### ISSUE TITLE
Visual Studio Test Explorer integration

### ISSUE THREAD

**Issue by BurtHarris** [PanayotCankov/mocha-typescript#10]
I just tried this package, it's great.    I like this style, and have existing JUnit tests I'll be porting, so this should save me some time and reduce frustration. Thank you.

I'm using Visual Studio Community Edition with the latest TypeScript for Visual Studio extension.   It integrates nicely with Mocha's describe/it style tests, even displaying a margin icon next to them to make it easy to run a particular test or suite.   Unfortunately, it doesn't recognize the mocha-typescript tests, and is initially surprised by the results.  (It does seem to adapt to their presence.)   

Are you aware of this, any plans to enhance the integration?

**Comment by PanayotCankov** [comment]
This is an interesting feature request. I don't have plans to implement it, but if I have some available time I will at least research if it can be done. I am not using Visual Studio any more. I moved to VSCode. It works well for TypeScript projects.

**Comment by BurtHarris** [comment]
Cool, thanks.   I'm using both VSCode and VS, and agree VSCode is nice environment.   But there are still some add-in packages only available for the full VS, e.g. Resharper, that don't (yet) seem to have open-source replacements.

**Comment by PanayotCankov** [comment]
- Text decoration extension for VSCode: https://github.com/Microsoft/vscode-extension-samples/blob/master/decorator-sample/extension.ts
 - Bootstrapping TypeScript project with AST traversal for test exploratio: https://github.com/FireSt-dead/tsc-native/blob/master/compile.java.ts

It should be possible to setup test exploration tool that takes a typescript project and figures out describe/it @sute/@test cases and decorates the it and the @test with red/green background color based on whether some tests passed failed. Also probably providing tooltips for errors with stack traces?

**Comment by PanayotCankov** [comment]
@BurtHarris I tried with VS2015 with node tools 1.2 I think. I only needed:
```
<TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
```
In the project and the VS was discovering new tests on save even with the @suite and @test decorators.
Double clicking on test was opening the test.js though but that was so even for tests created with describe and it.

I am closing this issue.
