### ISSUE TITLE
class/before/after timeout decorators

### ISSUE THREAD

**Issue by romancow** [PanayotCankov/mocha-typescript#12]
Love this approach to testing with TypeScript. I can't seem to find a great way of setting the timeout for an entire suite or for a class's `before` or `after` methods. Could the `timeout` decorator be extended to work in these instances as well?

**Comment by PanayotCankov** [comment]
I've just publish v1.0.12 it should handle @slow and @timeout for class (suite) and before/after methods.

**Comment by romancow** [comment]
Great, I'll check it out. Thanks for the update.
