### ISSUE TITLE
Make a compiler for mocha

### ISSUE THREAD

**Issue by PanayotCankov** [PanayotCankov/mocha-typescript#2]
Add `register` script that can register the typescript compiler as mocha compiler.

**Comment by ibratoev** [comment]
You should be able to use [ts-node](https://github.com/TypeStrong/ts-node) for that. It is not very well documented but this works: `mocha --compilers ts:ts-node/register`

**Comment by PanayotCankov** [comment]
Thanks, Probably I will :)

But there is some magic in there: https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L269 I got scared of. I used it in one of the projects I work on and it kept failing or it was doing multiple runs when I was working on multiple files, or it seemed to use somewhat cached versions of the test classes. I need to spend some more time to figure out what it is doing exactly and if the problem was on my side or in the ts-node.

Ultimately I would like to have a simple `tsc` performed, picking TS files from `tsconfig.json` and then a `mocha` which is something like: https://github.com/NativeScript/nativescript-cli/blob/master/dev/tsc-to-mocha-watch.js But I am not sure if I can put that into mocha's --compiler.

**Comment by ibratoev** [comment]
I had a similar problem and for it was because `tsc --watch` was compiling the .ts file to .js automatically. I fixed it by making sure mocha runs only the *.ts files:
```
mocha --compilers ts:ts-node/register test/*.ts
```

**Comment by PanayotCankov** [comment]
If this work it would be awesome, I guess I will just feed it with .ts files resolved from tsconfig.json

**Comment by PanayotCankov** [comment]
`mocha-typescript` now adds the `mocha-typescript-watch` script. It runs `tsc -w` in one process, watches its output and upon successful compilation runs `mocha` in another, concatenating the output of both. It is enabled by installing `mocha`, `typescript` and `mocha-typescript` as dev depenendencies, adding the npm script to your package json:
```
  "scripts": {
    "dev-test-watch": "mocha-typescript-watch"
  },
```
And calling `npm run dev-test-watch`.
You also need a `tsconfig.json` and a `test.ts` mocha entry-point.
