### ISSUE TITLE
Can suite contain suite? Just like describe contain describe

### ISSUE THREAD

**Issue by frogcjn** [PanayotCankov/mocha-typescript#3]
Can suite contain suite? Just like describe contain describe

**Comment by PanayotCankov** [comment]
We can try to device something around namespaces probably :+1:

**Comment by vekexasia** [comment]
I'm interested in this too.

**Comment by PanayotCankov** [comment]
@frogcjn @vekexasia 
I think u can currently use something like:
``` TypeScript
describe("outer suite", () => {
  @suite("inner suite") class InnerSute {
    @test testMethod() {}
  }
}
```
But this will create the InnerSuite class inside the scope of the function and will not be accessible outside (e. g. for extension).

Modules or namespaces can not be decorated.

I'd be happy to address this feature request, but I don't know how it would be best to handle it. Do you have any suggestions for syntax??

**Comment by PanayotCankov** [comment]
Ok, this would be the official suggestion:
```
describe("outer suite", () => {
    @suite("inner suite") class TestClass {
        @test method() {
        }
    }
});
```
