### ISSUE TITLE
target of ES6 does not work

### ISSUE THREAD

**Issue by edclement** [PanayotCankov/mocha-typescript#4]
if the typescript compiler is set to target es6, Mocha sees 0 tests. Guessing this is because the classes don't get converted to vanilla functions

**Comment by interisti** [comment]
+1

**Comment by PanayotCankov** [comment]
I will give it a try, the lib simply calls describe/it for classes and methods but doesn't actually passes the class function to mocha but rather wraps new and calls to the classes in functions.

**Comment by PanayotCankov** [comment]
I think ES6 decorators work a little bit differently. Currently the method decorators have the signature of property decorators, we should check it they are properly applied. Then when the class is decorated it enumerates its member to look for test methods, maybe ES6 methods should be enumerated using a different approach.

**Comment by PanayotCankov** [comment]
@edclement @interisti Targeting es6 should work as expected now.
