### ISSUE TITLE
before/after done callback support

### ISSUE THREAD

**Issue by interisti** [PanayotCankov/mocha-typescript#5]
Hi @PanayotCankov,
Thanks for the project, it really helps.

are done callback supported on before/after methods?
i tried:
```
@suite('some suite')
export class SomeTest {
  before(done) {
    // done is undefined here
  }
}
```

**Comment by PanayotCankov** [comment]
@interisti #6 adresses this, please check if it is ok for you. I am closing this issue.

**Comment by interisti** [comment]
@PanayotCankov  Perfect.
Thanks @Haringat
