### ISSUE TITLE
Could not find any test files matching pattern: test

### ISSUE THREAD

**Issue by oliverguhr** [PanayotCankov/mocha-typescript#9]
Hi, 
I created a toy project as described in the "Scafolding" section and it worked. 
But as soon as I rename the file to any other name than "test.ts" I get this error:

 npm test

> asd@1.0.0 test /source/mochaTypescript
> tsc -p . && mocha

Warning: Could not find any test files matching pattern: test
No test files found
npm ERR! Test failed.  See above for more details.

**Comment by PanayotCankov** [comment]
This is mocha specific I think. You can pass arguments to the `mocha` script. You can read some additional information in questions like this: http://stackoverflow.com/questions/10753288/how-to-specify-test-directory-for-mocha

Also I really like the MOCHA.OPTS here: https://mochajs.org
You can create a file where you can specify where are located your tests, modify reporters, etc.

**Comment by PanayotCankov** [comment]
Please if this satisfy your question, close the issue.

**Comment by oliverguhr** [comment]
This solved the problem. 

Unfurtunally I still can't get mocha-typescript running.
I am using systemjs as my module loader. Since moncha requires commonjs, I created a second tsconfig file that uses commonjs and sends the output to the "test" folder. 
I am now able to execute my tests with mocha directly if I invoke this:

`tsc  -p tsconfig.test.json && mocha test/ --colors`

Is it possible to add parameters to "mocha-typescript-watch" to invoke it with a custom tsconfig?

**Comment by PanayotCankov** [comment]
It should be easy to add. I just wonder how it would be most convenient.

**Comment by PanayotCankov** [comment]
Thanks to yargs now the following options are available:
```
Options:
  -p, --project  Path to tsconfig file or directory containing tsconfig, passed
                 to `tsc -p <value>`.                    [string] [default: "."]
  -t, --tsc      Path to executable tsc, by default points to typescript
                 installed as dev dependency. Set to 'tsc' for global tsc
                 installation.
                         [string] [default: "./node_modules/typescript/bin/tsc"]
  -o, --opts     Path to mocha.opts file containing additional mocha
                 configuration.          [string] [default: "./test/mocha.opts"]
  -m, --mocha    Path to executable mocha, by default points to mocha installed
                 as dev dependency.
                           [string] [default: "./node_modules/mocha/bin/_mocha"]
  -h, --help     Show help                                             [boolean]
```

You can set paths to special `mocha.opts` and `tsconfig.json` files in the npm scripts like:
```
  "scripts": {
    "dev-test-watch": "mocha-typescript-watch -p tsconfig.test.json -o mocha.opts"
  },
```

**Comment by PanayotCankov** [comment]
@oliverguhr better late than never :)
